### ISSUE TITLE
Link to Github repo from PyPI?

### ISSUE THREAD

**Issue by cdeil** [bmwant/leak#2]
Can you please add a link to this Github repo from PyPI?

I was looking at
https://pypi.python.org/pypi/leak/1.0.3
which links to a russian page and it wasn't obvious where to find the "leak" package.

**Comment by phoikoi** [comment]
fyi: The linked page is in Ukrainian, not Russian.  There's a (big) difference.  But I agree, there should be a link on the pypi page to github.

**Comment by cdeil** [comment]
> The linked page is in Ukrainian, not Russian. There's a (big) difference. 

Apologies!

**Comment by bmwant** [comment]
@cdeil @phoikoi sorry, my fault, just posted a link to my blog :octocat: Will update the page tomorrow.
